"""empty message

Revision ID: 3bc70b995221
Revises: ad8aa62d9a72
Create Date: 2019-08-09 22:44:01.655405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3bc70b995221'
down_revision = 'ad8aa62d9a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('client_id', sa.String(length=30), nullable=False))
    op.add_column('clients', sa.Column('created_at', sa.String(length=30), nullable=False))
    op.alter_column('clients', 'client_secret',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.drop_index('client_key', table_name='clients')
    op.drop_column('clients', 'client_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('client_key', mysql.VARCHAR(length=30), nullable=False))
    op.create_index('client_key', 'clients', ['client_key'], unique=True)
    op.alter_column('clients', 'client_secret',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.drop_column('clients', 'created_at')
    op.drop_column('clients', 'client_id')
    # ### end Alembic commands ###
