"""empty message

Revision ID: ad8aa62d9a72
Revises: 
Create Date: 2019-08-01 10:39:35.257084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad8aa62d9a72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_ibfk_1', 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key('books_ibfk_1', 'books', 'books', ['client_id'], ['id'])
    # ### end Alembic commands ###
